[WIP] Made Filters sidebar minimizeable on the Analysis tab
PathoTracker/Pathotracker pull request #100
Opened 2023-12-18 20:58 UTC by SeanKennyNF

2023-12-19 04:00 UTC, EliasPinno requested changes
How can I re-expand the filters after I close them? I can't figure it out, which means even if it is possible, it should be more obvious.

2024-01-03 21:00 UTC, SeanKennyNF commented on components/ui/data-table.tsx
> +      <div className="flex items-center justify-between py-4">
Tragic diff, I'd just check out the gif in the PR description honestly lol

2024-01-03 21:03 UTC, SeanKennyNF commented
> How can I re-expand the filters after I close them? I can't figure it out, which means even if it is possible, it should be more obvious.

@EliasPinno sorry for leaving you hanging! I wanted to merge the other one first and make changes to this one accordingly before pestering you again :)

The button is hanging out next to all the rest (Download CSV and columns). Does that location work for you or would you like to see the button somewhere else?

![Peek 2024-01-03 13-57](https://github.com/PathoTracker/Pathotracker/assets/86806388/da29d2c7-be51-4477-a4d8-a9f932dff369)

2024-01-06 17:59 UTC, EliasPinno approved these changes

2024-01-06 18:00 UTC, merged