Added Source Submission Popup
PathoTracker/Pathotracker pull request #131
Opened 2024-01-14 20:57 UTC by SeanKennyNF

Resolves #111 and adds the ability to submit a source to us from the front end!

2024-01-14 21:22 UTC, SeanKennyNF commented on app/pathogen/arbovirus/dashboard/(map)/MapArbovirusStudySubmissionPrompt.tsx
> +          Don&apos;t see an arbovirus study listed?
Copy and such pending feedback and subject to change fyi
https://3.basecamp.com/5061858/buckets/30589330/messages/6924228012

2024-01-14 21:22 UTC, SeanKennyNF commented on tailwind.config.js
> +        link: "#0000EE",
This is actually the recommendation from the HTML spec which is kind of interesting.
https://html.spec.whatwg.org/multipage/rendering.html#phrasing-content-3

2024-01-15 04:25 UTC, EliasPinno approved these changes

2024-01-16 07:56 UTC, HimanshuRanka requested changes

2024-01-16 07:56 UTC, HimanshuRanka commented on app/pathogen/arbovirus/dashboard/(map)/MapArbovirusStudySubmissionPrompt.tsx
> +        <Link className="inline text-link underline" href="https://forms.gle/pKNiMiMYr6hiKnXx8"> following form </Link>
link open on new tab is the only thing to be added. Mairead will be able to guide on the decision making for the copy

2024-01-19 05:10 UTC, HimanshuRanka approved these changes

2024-01-20 16:28 UTC, merged